
from unittest.mock import DEFAULT


ADMIN_ROLE = 1
USER_ROLE = 0 
OTHER_ROLE = 2

ROLE_TYPE = [ADMIN_ROLE, USER_ROLE, OTHER_ROLE]

POST = "POST"
USER = "USER"
CATEGORY = "CATEGORY"
TAG = "TAG"

FACEBOOK_PROVIDER = "FACEBOOK"
GOOGLE_PROVIDER = "GOOGLE"
USER_PROVIDER = "USER"

DEFAULT_AVATAR = "https://res.cloudinary.com/nhat-duy/image/upload/v1699412601/img/x1ihwbrd4couaakietiz.jpg"