
ADMIN_ROLE = 1
USER_ROLE = 0 
OTHER_ROLE = 2

ROLE_TYPE = [ADMIN_ROLE, USER_ROLE, OTHER_ROLE]

POST = "POST"
USER = "USER"
CATEGORY = "CATEGORY"
TAG = "TAG"

FACEBOOK_PROVIDER = "FACEBOOK"
GOOGLE_PROVIDER = "GOOGLE"
USER_PROVIDER = "USER"